<a href="https://colab.research.google.com/github/amir-b-mostaghimi/Tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introduction to Tensors with 'tf.constant'

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [3]:
#Creating tensors with tf.constants()
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check the number of dimesion of a tensor (ndim is the number of dimensions)
scalar.ndim

0

In [5]:
# create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#chect the dimnsion of the vector
vector.ndim

1

In [9]:
#Create a matrix
matrix = tf.constant ([[10,7],
                       [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [13]:
#create another matrix
another_matrix= tf.constant([[10., 7.],
                             [3.,2.],
                             [8.,9.]], dtype=tf.float16) # specify the data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
another_matrix.ndim

2

In [17]:
# create a tensor
tensor= tf.constant ([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [21]:
tensor.ndim

3

What learned:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers ( where n can be any number, 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

## Creating tensors with 'tf.cariable'

In [28]:
changeable_tensor= tf.Variable([10,7])
unchangable_tensor= tf.constant([10,7])
changeable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [26]:
# Let's try to to change an element in changeable Tensor
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's do the same with the unchangeable_tensor
unchangable_tensor[0].assign(7)
# Some of the tensors need to be changed an some of them need to remain constant. Although we do not make the decision it is useful to see it in action.