<a href="https://colab.research.google.com/github/amir-b-mostaghimi/Tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introduction to Tensors with 'tf.constant'

In [50]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [51]:
#Creating tensors with tf.constants()
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [52]:
#check the number of dimesion of a tensor (ndim is the number of dimensions)
scalar.ndim

0

In [53]:
# create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [54]:
#chect the dimnsion of the vector
vector.ndim

1

In [55]:
#Create a matrix
matrix = tf.constant ([[10,7],
                       [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [56]:
matrix.ndim

2

In [57]:
#create another matrix
another_matrix= tf.constant([[10., 7.],
                             [3.,2.],
                             [8.,9.]], dtype=tf.float16) # specify the data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [58]:
another_matrix.ndim

2

In [59]:
# create a tensor
tensor= tf.constant ([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [60]:
tensor.ndim

3

What learned:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers ( where n can be any number, 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

## Creating tensors with 'tf.cariable'

In [28]:
changeable_tensor= tf.Variable([10,7])
unchangable_tensor= tf.constant([10,7])
changeable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [26]:
# Let's try to to change an element in changeable Tensor
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's do the same with the unchangeable_tensor
unchangable_tensor[0].assign(7)
# Some of the tensors need to be changed an some of them need to remain constant. Although we do not make the decision it is useful to see it in action.

## Creating random tensors

**Note:** Rarely in practice you need to decide weather to use 'tf.constant' or 'tf.Variable' to create tensors, as TensorFlow does that for you. However, if in doubt, use 'tf.constant' and change it later if needed.


Random tensors are tensors of some abitrary size which contain random numbers.

In [31]:
# create two random tensors
random_1= tf.random.Generator.from_seed(42)
random_1= random_1.normal(shape=(3,2))

random_2= tf.random.Generator.from_seed(42)
random_2= random_2.normal(shape=(3,2))

# Are they equal?:
random_1, random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the orther of elements in a tensor


If the data is in order, it may impact the accuracy of the learning. So we need to shuffle the data as needed.

In [37]:
# Shuffle a tensor (Valuable for when you want to shuffle your data so the inherent order does not effect the learning)
not_shuffled= tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled.ndim
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [38]:
# Shuffle (suffling along the first dimension)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [62]:
tf.random.set_seed(42) #Global level random seed
tf.random.shuffle(not_shuffled, seed= 42) #operation level random seed
# since the initial guess is a randomly genarated tensor, each run will start with a different initail guess and result in a different output. Therefore we need to introduce a certain level of stability to the initial guesses.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Other ways to make tensors

In [64]:
tf.ones([10, 7])
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [73]:
# you can also turn numy arrays into tensors
# The main difference between Numpy arrays and Tensorflow tensors is the later one is much faster on GPUs
import numpy as np

Numpy_A= np.arange (1,25, dtype=np.int32)
tf.constant(Numpy_A, shape =(2,3,4))
#2 x 3 x 4 =24 == number of elemetns 

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting information from tensors